In [ ]:
import numpy as np
# creating arrays
arr =np.array([1, 2, 3, 4, 5],dtype=float)
print(arr)
zeros_arr = np.zeros((3, 3), dtype=int)
print(zeros_arr)
ones_arr =np.ones((2, 2), dtype=int)
print(ones_arr)

arange_arr = np.arange(20)
print(arange_arr)
reshaped_arr=arr.reshape(5, 1)
print(reshaped_arr)
sliced_arr = arr[2:4]
print(sliced_arr)
reshaped_arr=arr.reshape(5, 1)
print(reshaped_arr)
sliced_arr = arr[2:4]
print(sliced_arr)
a=np.array([1,2,3,4,5,6,7,8])
b=a.T
print(b)
b=np.split(a,4)
print(b)
a=np.array([1,2,3,4,5,6,7,8])
b=a.T
print(b)
b=np.split(a,4)
print(b)
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
d=np.linalg.eig(c)
print(d)


[1. 2. 3. 4. 5.]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[3. 4.]
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[3. 4.]
[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[[19 22]
 [43 50]]
EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:
import numpy as np
data = np.loadtxt("/content/drive/MyDrive/dataset/dap.txt",dtype=int)
d=np.savetxt("/content/drive/MyDrive/dataset/dap.txt",data)
print(d)
print(data)

None
[122333333    122334      1234]


In [ ]:
arange_arr=np.arange(0,100,5)
print(arange_arr)
c=np.savetxt("/content/vija.txt",arange_arr)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
a=np.array([[1,2],[3,4]])
print(a.shape)

(2, 2)


In [ ]:
from numpy
a=np.array([2,3,4,,5,6,,3,4,8])
a.resize(4,5)
print(a.shape)


SyntaxError: invalid syntax (<ipython-input-70-fc98580e581c>, line 1)

In [ ]:
import numpy as np
arange_arr = np.arange(30).reshape(2,3,5)
print(arange_arr)
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[2 3 5 6 5 7]]]


number of rows become number od group
col
um becomes rows
group became colum

In [ ]:
a1=np.

In [ ]:
a=10
b=20
c=a+b
print(c)


30


In [ ]:
a=10
b=20
c=a*b
print(c)

200


In [ ]:
import numpy as np
a1=np.full((2,2),3)
print(a1)
print(a1.itemsize)

[[3 3]
 [3 3]]
8


In [ ]:
import numpy as np
x=[1,2,3]
a=np.array(x)
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x, y))
print(np.outer())